### ISSUE TITLE
404

### ISSUE THREAD

**Issue by MIKUKANO** [Sakamakiiizayoi/ttorc_auto#5]
大佬，问一下这个是什么情况😰
虽然签到是正常的（用的人人）
![IMG_1747](https://github.com/user-attachments/assets/9bd1950e-a552-4942-b710-cfb1f710a5bd)

**Comment by Sakamakiiizayoi** [comment]
如果之前是正常使用的话 那么大概率只是打码服务挂了不用管

**Comment by MIKUKANO** [comment]
> 如果之前是正常使用的话 那么大概率只是打码服务挂了不用管

明白了，谢谢大佬
